services:
  - type: web
    name: lotr-chars
    runtime: node
    buildCommand: npm install
    startCommand: npx cds deploy --to sqlite && node server.js
    envVars:
      - key: NODE_ENV
        value: production
